// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBOzj80nBtHMfxBCCJVG9KSCtno30z4F8',
    appId: '1:42894006122:web:f982fab8e816e4176b7713',
    messagingSenderId: '42894006122',
    projectId: 'my-tindahance-7216e',
    authDomain: 'my-tindahance-7216e.firebaseapp.com',
    storageBucket: 'my-tindahance-7216e.firebasestorage.app',
    measurementId: 'G-249X9XCX0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_U6WT5bLDgMkqYUssSWM87ejCy4lR0YQ',
    appId: '1:42894006122:android:308be810204591ea6b7713',
    messagingSenderId: '42894006122',
    projectId: 'my-tindahance-7216e',
    storageBucket: 'my-tindahance-7216e.firebasestorage.app',
  );
}
